# Generated by Django 5.1.4 on 2025-01-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0012_rename_color_car_color_ext_car_color_int_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possiblebuyer',
            name='cedula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
