# Generated by Django 5.1.4 on 2025-01-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0013_possiblebuyer_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='possiblebuyer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
