# Generated by Django 5.1.4 on 2025-01-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0014_possiblebuyer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possiblebuyer',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
