# Generated by Django 5.1.4 on 2025-01-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0018_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='possiblebuyer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
