# Generated by Django 5.1.4 on 2025-02-01 01:12

import d_store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0019_possiblebuyer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=d_store.models.get_default_image, null=True, upload_to='part_images'),
        ),
    ]
