# Generated by Django 5.1.4 on 2025-01-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_payments', '0002_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
