# Generated by Django 5.1.4 on 2025-01-19 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_payments', '0004_invoinceproduct'),
        ('d_store', '0017_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoinceproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_invoice', to='d_store.product'),
        ),
    ]
